### PR TITLE
Change labs-experiment to labs-post

### PR DESCRIPTION
**Pull request by nlisgo**
This is just the minimal changes needed. More refactoring will be done post launch

### CODE REVIEW

**Comment by giorgiosironi** [comment]
From what I understand this will become green once the api-raml is changed.

**Comment by nlisgo** [comment]
@giorgiosironi that is my understanding. It doesn't surprise me that it failed CI without this update.

**Comment by giorgiosironi** [comment]
Pushed the update to api-raml in the composer.lock, but conflicts with `develop`. Since more than one person is using this branch, I will merge `develop` and update again rather then rebasing, which would be dangerous.

**Comment by giorgiosironi** [comment]
Updated api-raml, but there were two tests failing. The first one was an obvious change, trying to patch the second which seems related to the `type` field coming out of the API.

**Comment by giorgiosironi** [comment]
I am adding commits trying to fix the `type` fields, but they can be dropped or reverted later if they don't help.

**Comment by giorgiosironi** [comment]
Green, but needs the review of @nlisgo

**Pull request merged**
