### PR TITLE
Remove project dependency on api-dummy for tests

### PR DESCRIPTION
**Pull request by nlisgo**
This should remove the need for api-dummy to be available for the `./project_tests.sh` to run.

cc @lsh-0 I have wanted to do this since the issues that we experienced on the PHP 7.2 update. There shouldn't be a requirement for api-dummy.

### CODE REVIEW

**Comment by lsh-0** [comment]
Looks like there are local modifications on `journal-cms--ci`:

```

[2020-10-07T19:34:45.927Z] [54.227.162.57] out: ----------
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:           ID: api-dummy-repository-reset
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:     Function: cmd.run
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:         Name: cd /srv/api-dummy && git checkout master
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:       Result: False
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:      Comment: Command "cd /srv/api-dummy && git checkout master" run
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:      Started: 19:21:54.692722
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:     Duration: 808.781 ms
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:      Changes:   
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:               ----------
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:               pid:
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   2461
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:               retcode:
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   1
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:               stderr:
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   error: Your local changes to the following files would be overwritten by checkout:
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	composer.lock
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/digests/34873b4d2390.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/digests/b518a9d89f36.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/digests/bf88371b1136.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/digests/f0f08e8d6ee3.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/recommendations/article-16412.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	src/bootstrap.php
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	test/SmokeTest.php
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   Please commit your changes or stash them before you switch branches.
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   error: The following untracked working tree files would be overwritten by checkout:
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/articles/15691.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/articles/36258.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/articles/40684.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/articles/53433.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/articles/55774.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   	data/recommendations/article-45562.json
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   Please move or remove them before you switch branches.
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:                   Aborting
[2020-10-07T19:34:45.927Z] [54.227.162.57] out:               stdout:
```

I'll revert the changes and kick the build.

**Comment by lsh-0** [comment]
all green

**Comment by lsh-0** [comment]
> cc @lsh-0 I have wanted to do this since the issues that we experienced on the PHP 7.2 update. There shouldn't be a requirement for api-dummy.

You would know best what is best for journal-cms here. 

The important thing is that it continues participating in the end2end integration testing.

Is this tied to an issue? If so, let me know when it's done and I'll open a ticket to remove api-dummy from the journal-cms formula. This will also make containerisation simpler.

**Comment by nlisgo** [comment]
> Is this tied to an issue? If so, let me know when it's done and I'll open a ticket to remove api-dummy from the journal-cms formula. This will also make containerisation simpler.

Thinking about this a little more, for local development it may still be useful to have the `api-dummy` available but we shouldn't need it in any environment other than the local dev. `./project_tests.sh` should not rely on it so I will merge this in. We should change the formula to not require api-dummy in ci. Maybe, we should just remove it from all instances, add it back in after the docker move if it is missed in the local development process. I will create a ticket for this.

**Comment by nlisgo** [comment]
@lsh-0 here is the ticket for it: https://github.com/elifesciences/issues/issues/6188

**Comment by nlisgo** [comment]
> The important thing is that it continues participating in the end2end integration testing.

This is the case and it is not reliant on `api-dummy` in `end2end`.

**Comment by nlisgo** [comment]
I'm going to but this PR under more scrutiny Friday morning before I hit the merge button.

**Pull request merged**
