### PR TITLE
Create event content type and rest resource

### PR DESCRIPTION
**Pull request by nlisgo**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The build fails with `Unable to install the geofield module since it does not exist.`

Is it at the PHP/Composer level or is there any Ubuntu package you need to be added to the EC2 instances?

**Comment by nlisgo** [comment]
@giorgiosironi I will address this. It was a module that I installed at one stage and have not removed all references to it.

**Comment by giorgiosironi** [comment]
To build this I added https://github.com/elifesciences/journal-cms-formula/commit/235e458ea88bd6a100b5c1ee0ebcfc6148566b7b which does the same thing as the Travis build.

It is unclear which version of Puli this project uses?
- the `curl https://puli.io/installer | php` installs `1.0.0-beta10` globally
- `composer.json` requires `puli/cli` as `1.0.x-dev`
- `composer.lock` requires `puli/cli` as `dev-master` and in fact Composer complains about it being not up to date with `composer.json`

**Comment by nlisgo** [comment]
@giorgiosironi I will look into the version conflicts in a future piece of work. Thanks for clearing the break on alfred.

**Pull request merged**
