### PR TITLE
Add reproducibility project cancer biology collection

### PR DESCRIPTION
**Pull request by nlisgo**
Do we need to add in the replication studies also? I have not yet, I will await instructions.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
They should be there too, so the order is 07072, 21253, 06959, 17584 etc.

**Comment by nlisgo** [comment]
@sianroderick who should the curator be for this collection? Each collection requires at least one curator.

**Comment by sianroderick** [comment]
We need all articles present - including the Editorials, Insights and Feature Articles.

I'll check with Andy/Peter to find out who the curator should be.

**Comment by nlisgo** [comment]
@sianroderick @thewilkybarkid all articles (including the Editorials, Insights and Feature Articles) should now be present in the list in the expected order.

We just need to assign a curator. Currently, the curator is not optional so I need to assign one. I suggest we merge this in with an arbitary curator and resolve the issue before going live.

**Pull request merged**
