### PR TITLE
ELPP-2429 Remove Puli

### PR DESCRIPTION
**Pull request by thewilkybarkid**

### CODE REVIEW

**Comment by nlisgo** [comment]
I'll give this a test run tomorrow.

**Comment by jamiehollern** [comment]
🍾

**Comment by thewilkybarkid** [comment]
Good to go. The `puli-master` state will need removing form the formula.

**Comment by nlisgo** [comment]
All looks good to me!!

**Comment by nlisgo** [comment]
I removed my local `.puli` folder did:

```
vagrant destroy
vagrant clean-up
COMPOSER=composer-setup.json composer install
vagrant up
```

Witnessed a failed validation by removing an expected property from an API response. Happy with this.

Goodbye puli!!

**Comment by giorgiosironi** [comment]
I'll merge then, and remove the state from the formula.

**Pull request merged**
