### PR TITLE
Feature: bumps mentions of php7.0 to php7.2 in composer.json

### PR DESCRIPTION
**Pull request by lsh-0**
This is a *very* naive 'fix' for getting the journal-cms project building on Ubuntu 18.04 with php7.2

I was encountering the error:

```php
Fatal error: Declaration of Drupal\field_validation\Form\FieldValidationRuleAddForm::buildForm(array $form, Drupal\Core\Form\FormStateInterface $form_state, ?Drupal\field_validation\FieldValidationRuleSetInterface $field_validation_rule_set = NULL, $field_validation_rule = NULL) must be compatible with Drupal\field_validation\Form\FieldValidationRuleFormBase::buildForm(array $form, Drupal\Core\Form\FormStateInterface $form_state, ?Drupal\field_validation\FieldValidationRuleSetInterface $field_validation_rule_set = NULL, $field_validation_rule = NULL, $field_name = '') in /ext/srv/journal-cms/web/modules/contrib/field_validation/src/Form/FieldValidationRuleAddForm.php on line 18
Drush command terminated abnormally due to an unrecoverable error.                                                                                             ?[31;40m?[1m[error]?[0m
Error: Declaration of Drupal\field_validation\Form\FieldValidationRuleAddForm::buildForm(array $form, Drupal\Core\Form\FormStateInterface $form_state,
?Drupal\field_validation\FieldValidationRuleSetInterface $field_validation_rule_set = NULL, $field_validation_rule = NULL) must be compatible with
Drupal\field_validation\Form\FieldValidationRuleFormBase::buildForm(array $form, Drupal\Core\Form\FormStateInterface $form_state,
?Drupal\field_validation\FieldValidationRuleSetInterface $field_validation_rule_set = NULL, $field_validation_rule = NULL, $field_name = '') in
/ext/srv/journal-cms/web/modules/contrib/field_validation/src/Form/FieldValidationRuleAddForm.php, line 18
```
in this state:
```
----------
          ID: site-configuration-import
    Function: cmd.run
        Name: ../vendor/bin/drush config-import -y
```

There were some similar sounding issues online and the drupal community seemed to be on top of them, so I upgraded the dependencies and the command the state was running was no longer failing

### CODE REVIEW

**Comment by lsh-0** [comment]
kick this when formula is passing: https://github.com/elifesciences/journal-cms-formula/pull/39/files

**Comment by giorgiosironi** [comment]
Is this backward compatible? Because the current servers only have PHP 7.0 available. So the code should be kept compatible with both 7.0 and 7.2 until the end of the transition?

**Comment by giorgiosironi** [comment]
I think running this PR broke `journal-cms--ci`, I have reset it with `rm -rf /srv/journal-cms`.

**Comment by lsh-0** [comment]
> Is this backward compatible?

not sure, but I've but reverted the composer.json `7.2` change I made to `7.0` again. Composer may have seen that value and installed different versions of dependencies ...?

**Comment by lsh-0** [comment]
some new errors:

```
----------
          ID: site-install
    Function: cmd.run
        Name: ../vendor/bin/drush site-install config_installer -y
####test -e /home/elife/site-was-installed.flag && ../vendor/bin/drush cr || echo "site was not installed before, not rebuilding cache"
#../vendor/bin/drush cr # may fail with "You have requested a non-existent service "cache.backend.redis"
redis-cli flushall

      Result: True
     Comment: Command "../vendor/bin/drush site-install config_installer -y
              ####test -e /home/elife/site-was-installed.flag && ../vendor/bin/drush cr || echo "site was not installed before, not rebuilding cache"
              #../vendor/bin/drush cr # may fail with "You have requested a non-existent service "cache.backend.redis"
              redis-cli flushall
              " run
     Started: 00:45:10.689150
    Duration: 2057.533 ms
     Changes:   
              ----------
              pid:
                  3648
              retcode:
                  0
              stderr:
                  Starting Drupal installation. This takes a while. Consider using the        [ok]
                  --notify global option.
                  Drush command terminated abnormally due to an unrecoverable error.       [error]
              stdout:
                  You are about to DROP all tables in your 'elife_2_0' database. Do you want to continue? (y/n): y
                  TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::reset() must be an instance of Doctrine\Common\Annotations\void, none returned in Doctrine\Common\Annotations\AnnotationRegistry::reset() (line 55 of /ext/srv/journal-cms/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php).
                  OK
----------

```

**Comment by lsh-0** [comment]
@nlisgo , if you could take a look at what is happening, I'd be grateful. The changes I've made make it work under php 7.2 , but it can't get past installation.

**Comment by giorgiosironi** [comment]
@nlisgo is off ill today, so there will be no updates on this front for now.

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/test-journal-cms/604/ broken again for some reason, deleting `vendor/`

**Comment by lsh-0** [comment]
> @nlisgo is off ill today, so there will be no updates on this front for now.

ah, no worries. hope @nlisgo feels better soon

**Comment by lsh-0** [comment]
> broken again for some reason, deleting vendor/

is it this PR that is breaking `--ci` ? I'll leave it be until Nathan can weigh in on what is wrong

**Comment by giorgiosironi** [comment]
I think so, haven't seen anything else that changes the `composer`-installed libraries.

**Pull request closed without merging**
