### PR TITLE
Fix for null image style objects.

### PR DESCRIPTION
**Pull request by jamiehollern**
@giorgiosironi @stephenwf

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This didn't run because I locked `journal-cms--ci` for debugging, unblocking and building now.

**Comment by giorgiosironi** [comment]
And it's now green on Jenkins, making the build stable in spite of an existing database. Other PRs should rebase or merge `develop` after this has got in.

**Comment by jamiehollern** [comment]
@giorgiosironi Can we get this merged in then?

**Comment by giorgiosironi** [comment]
I think so.

**Comment by giorgiosironi** [comment]
By the way this coveralls bot does not seem to give us useful feedback, it's always red because coverage goes down 0.001%?

**Comment by giorgiosironi** [comment]
(I don't see coverage as a particularly interesting metric for this project)

**Comment by jamiehollern** [comment]
@giorgiosironi Agreed on both points. We can talk to @nlisgo about it when he's back perhaps.

**Comment by stephenwf** [comment]
The way I've seen it being used on other projects is to tackle back logs of coverage with each merge, so even if the coverage for this commit doesn't need covered the whole project is raised. Might not fit our use-case though

**Pull request merged**
