### PR TITLE
Add editor role and set field permissions on subject id field

### PR DESCRIPTION
**Pull request by nlisgo**
@jamiehollern

### CODE REVIEW

**Comment by giorgiosironi** [comment]
:+1: subjects in line with the expectation of articles

**Comment by jamiehollern** [comment]
👍

**Comment by giorgiosironi** [comment]
There is some problem with the `journal--ci` EC2 instance, which doesn't boot. Looking into it...

**Comment by giorgiosironi** [comment]
Now green on Alfred too.

**Comment by nlisgo** [comment]
@giorgiosironi I'm hoping that this work will clear the way for better support of subject ids in the related applications. Please confirm or let me know what more can be done.

**Comment by giorgiosironi** [comment]
Will try to integrate this tomorrow after lax-bot, thanks :+1:

**Pull request merged**
