### PR TITLE
INTRA-2276 Added Redis caching to Journal CMS and Drupal VM.

### PR DESCRIPTION
**Pull request by jamiehollern**
@nlisgo @giorgiosironi I also updated the Composer dependencies as the lock file was out of date.

The following changes should be added to the formula's `settings.php`:

```
$settings['cache']['default'] = 'cache.backend.redis';
$settings['redis.connection']['interface'] = 'PhpRedis';
$settings['redis.connection']['host'] = '127.0.0.1';
$settings['cache']['bins']['bootstrap'] = 'cache.backend.chainedfast';
$settings['cache']['bins']['discovery'] = 'cache.backend.chainedfast';
$settings['cache']['bins']['config'] = 'cache.backend.chainedfast';
$settings['container_yamls'][] = 'modules/redis/example.services.yml';
```

Note that the Drupal module currently only supports the `PhpRedis` PHP extension, and not the `Predis` extension. Sharding is not supported currently either.

To test that this is working inside Drupal-VM once installed and configured, use `redis-cli` and run `KEYS *`. This will show a list of Drupal keys.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The settings seem constant and identical for all machines, so you can go to https://github.com/elifesciences/journal-cms-formula/blob/master/salt/journal-cms/config/srv-journal-config-local.settings.php and add them in a pull request. I'll review and merge.

**Comment by jamiehollern** [comment]
@giorgiosironi Pull request up https://github.com/elifesciences/journal-cms-formula/pull/13

**Comment by giorgiosironi** [comment]
Re-running the build now that the formula contains the configuration.

**Comment by giorgiosironi** [comment]
The new `config/local.settings.php` are in place, but the fresh site install also fails here because:
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:    [error]
12:37:48 [54.198.202.212] out:                   You have requested a non-existent service "cache.backend.redis". Did
12:37:48 [54.198.202.212] out:                   you mean one of these: "cache.backend.apcu", "cache.backend.php",
12:37:48 [54.198.202.212] out:                   "cache.backend.memory"? 
```
@jamiehollern what is the problem?

**Comment by jamiehollern** [comment]
@giorgiosironi It seems like the service isn't available at the time of install because the `settings.php` is created before the configuration is imported which means that the module isn't installed, so it does make sense. 

I'll make the lines in `settings.php` conditional on the cache backend being available, but log when it isn't to ensure we know if it's not available post-install.

**Comment by thewilkybarkid** [comment]
We had to do something similar on the old site: https://github.com/elifesciences/elife-website/blob/develop/src/settings.php#L89-L100

**Comment by jamiehollern** [comment]
@thewilkybarkid That's interesting, I'll have a look. Thanks.

**Comment by giorgiosironi** [comment]
Had to comment out the settings because they were breaking end2end and prod. Can we have a "preparatory" version of this that can be merged and working without the settings, so that will be able to add them later?

**Comment by jamiehollern** [comment]
@giorgiosironi This is fixed now. Ready for merge.

**Comment by giorgiosironi** [comment]
Will merge after testing http://jira.elifesciences.org:8080/browse/ELPP-1459 so not to do things at once.

**Comment by giorgiosironi** [comment]
Test done on ELPP-1459 with some things to improve, let's go ahead with this.

**Comment by jamiehollern** [comment]
@giorgiosironi Great stuff. We need to ensure the formula is updated again or this will cause errors.

**Comment by giorgiosironi** [comment]
I am following as it gets through the different environments.

**Comment by giorgiosironi** [comment]
Strangely 151 got through ci without errors: https://ci--alfred.elifesciences.org/job/test-journal-cms/
Let's see what the other environments do.

**Comment by giorgiosironi** [comment]
And also end2end :thinking: maybe it has some defaults?

**Comment by giorgiosironi** [comment]
Green on all environments. Adding the settings now, and rerunning the same commit through all the environments.

**Comment by giorgiosironi** [comment]
Ok, https://ci--alfred.elifesciences.org/job/test-journal-cms/152/consoleFull failed with the standard:
```
17:09:47 [54.87.224.16] out:                   Starting Drupal installation. This takes a while. Consider using the        [ok]
17:09:47 [54.87.224.16] out:                   --notify global option.
17:09:47 [54.87.224.16] out:                   Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:    [error]
17:09:47 [54.87.224.16] out:                   You have requested a non-existent service "cache.backend.redis". Did
17:09:47 [54.87.224.16] out:                   you mean one of these: "cache.backend.apcu", "cache.backend.php",
17:09:47 [54.87.224.16] out:                   "cache.backend.memory"?
```
I thought we needed some modification to settings.php in the formula to make this work?

**Pull request merged**
