### PR TITLE
Unpublish blog-articles

### PR DESCRIPTION
**Pull request by nlisgo**

### CODE REVIEW

**Comment by nlisgo** [comment]
The CI failure seems unrelated to this PR and the step that it's failing at seems to be a CI setup step indicating that all PR's will fail. @lsh-0 please can you take a look.

**Comment by lsh-0** [comment]
sure thing. I've [opened a ticket](https://github.com/elifesciences/issues/issues/5666) for this build and the other one that is failing.

When it's fixed I'll see this build is re-run

**Comment by nlisgo** [comment]
> sure thing. I've [opened a ticket](https://github.com/elifesciences/issues/issues/5666) for this build and the other one that is failing.
> 
> When it's fixed I'll see this build is re-run

Thanks for sorting it!

**Comment by nlisgo** [comment]
@lsh-0 once this is deployed I will need to trigger a search re-index.

There still hasn't been a successful run of the re-index here: https://alfred.elifesciences.org/job/process/job/process-search-reindex/

I will attempt it.

**Comment by lsh-0** [comment]
> There still hasn't been a successful run of the re-index here:

Didn't realise it was necessary.

**Comment by nlisgo** [comment]
> > There still hasn't been a successful run of the re-index here:
> 
> Didn't realise it was necessary.

Not necessary, just makes me a little concerned that it won't work when I press the button. It's running now.

**Comment by lsh-0** [comment]
I think the timeout is too short. I'm run off my feet at the moment and haven't had a chance to look at it today

**Comment by nlisgo** [comment]
> I think the timeout is too short. I'm run off my feet at the moment and haven't had a chance to look at it today

Hopefully, it will run right now. And then I won't need to hit that button again in a long time!

**Comment by nlisgo** [comment]
Search re-index failed :(

https://alfred.elifesciences.org/job/process/job/process-search-reindex/7/execution/node/26/log/?consoleFull

**Comment by nlisgo** [comment]
There are redirects in place for the 3 unpublished blog articles so we can live with this until next week. Have a great weekend @lsh-0.

**Comment by lsh-0** [comment]
a re-index looks like it's happening on `search--prod` right now

did you start it manually?

```
elife@prod--search:/srv/search$ php bin/console keyvalue:load index-metadata
array (
  'write' => 'elife_search_reindex_7',
  'read' => 'elife_search_reindex_6',
  'last_import' => '20181112173000',
)
```

**Comment by nlisgo** [comment]
> a re-index looks like it's happening on `search--prod` right now
> 
> did you start it manually?

I triggered it here: https://alfred.elifesciences.org/job/process/job/process-search-reindex/7/

**Pull request merged**
